### ISSUE TITLE
it has no way to insert entity with id.

### ISSUE THREAD

**Issue by jiqimaogou** [pardom/Ollie#38]
if I have an entity with id value, when I call save, it could not be inserted into the database. can you provide ```model.replace()``` method? 

when the contentprovider is supported, everytime I save the entity, it will call ```notifychange()```, sometimes, I want to insert a list of entities into the database, it will call ```notifychange()``` many times, can you provide some funtion to prevent ```notifychange()```.

**Comment by lauw** [comment]
I agree on the whole Id thingy, alot of my models use an Id field, and I have to replace it with something else since you are already using Id as an attribute, which makes Gson fail with parsing.

Right now I've marked all attributes with the gson Expose annotation, so it will ignore your id field and use mine instead. (alot of work)

Also, the save() method says it will insert or update, and I'm not sure if it does, but it throws alot of errors into my console for failing to match Unique constraints.

**Comment by pardom** [comment]
@jiqimaogou `_id` as the primary auto-incrementing key on a table is a requirement of Ollie as it is a requirement of using content providers. This is also how Ollie is able to do references. If you have a primary key from an external model, you can store that as a unique column in your Ollie model.

@lauw coupling the database schema to the API structure seems like bad design. SQL is relational, and the API response is likely not. What if the API changes? What if you want to change APIs? These may be in your control, but since it's not good design to tightly couple your database and network, Ollie doesn't make considerations for that.

What I do with my projects is separate the app model and API model, but provide an easy way to map them. For example:

```java
class ApiMessage {
	public String id;
	public String text;
}

@Table("Message")
class Message extends Model {
	@Column("messageId")
	public String messageId;
	@Column("text")
	public String text;
	
	public Message() {
	}
	
	public Message(ApiMessage apiMessage) {
		messageId = apiMessage.id;
		text = apiMessage.text;
	}
}
```

**Comment by mrkma** [comment]
@lauw a nice solution would be to do this, it skips out fields defined in 'Model' during serialization/deserialization.

        ExclusionStrategy strategy = new ExclusionStrategy() {
            @Override
            public boolean shouldSkipField(FieldAttributes f) {
                return f.getDeclaringClass().equals(Model.class);
            }

            @Override
            public boolean shouldSkipClass(Class<?> clazz) {
                return false;
            }
        };
        Gson gson = new GsonBuilder()
                .addDeserializationExclusionStrategy(strategy)
                .addSerializationExclusionStrategy(strategy)
                .create();

I had the same issue and thankfully due to this feature I don't have to add an annotation to every field just to support Retrofit (and thus Gson).

**Comment by lauw** [comment]
Thanks for the follow up. Gonna give that a try when I get the chance :+1:
